version: "3.4"
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.2
    restart: on-failure:0
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./data"
      ENABLE_MODULES: text2vec-openai
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      OPENAI_APIKEY: ${OAI_KEY}
      OPENAI_ORGANIZATION: ${OAI_ORG}
      CLUSTER_HOSTNAME: "node1"
